### ISSUE TITLE
Upgrade version via mysql_upgrade

### ISSUE THREAD

**Issue by R-omk** [docker-library/percona#20]
https://github.com/docker-library/mysql/issues/130

In this example CMD is 'bash' and  mysql_upgrade started manually

```
root@321568b77f23:/# mysql_upgrade
Looking for 'mysql' as: mysql
Looking for 'mysqlcheck' as: mysqlcheck
Error: Failed while fetching Server version! Could be due to unauthorized access.
FATAL ERROR: Upgrade failed

```

How to run the mysql_upgrade ?

**Comment by netpoe** [comment]
I ran into the same problem, this worked for me: 

```
docker exec -it container_name bash -c "mysql_upgrade -uroot -proot"
```

`root` must be your mysql username and password
