### ISSUE TITLE
percona 5.7 is started using systemd

### ISSUE THREAD

**Issue by EugenMayer** [docker-library/percona#24]
Seems like after installing percona 5.7 we miss a 

```
RUN systemctl disable mysql
```

Otherwise the mysqld server is started using systemd all the time, not using the entrypoint

**Comment by tianon** [comment]
I'm not sure I'm understanding the issue entirely, can you elaborate on how you're starting the container and what's happening?

We don't run `systemd` in the image, so it shouldn't ever be launching anything, but besides that, our base image has `policy-rc.d` in place (https://github.com/docker/docker/blob/cccfe63e86f3842a2139d8b9c24bfab5be7639b8/contrib/mkimage/debootstrap#L38-L49), which is designed to prevent service startup in appropriately-behaved packages.

**Comment by EugenMayer** [comment]
@tianon i think it was rather my fault and a wrong assumption on my side. I had a doubled mysqld process running, one "mysqld" and one "mysqld --no-networking".

My assumption was, that systemd started one of those, since running systemd status on mysqld ruturend "enabled". But it turned out to be not the reason.

The reason was, i used a docker-entrypoint.d/ script to populate the random-generate mysql password into consul, used exit 0 there. This, the way those script are exectured, actually exited the docker-entrypoint.sh instead of the "help script in .d" and that left over the mysql --no-networking process during docker-entrypoint.sh startup.

From my perspective, this issue can be closed

**Comment by EugenMayer** [comment]
i guess i shall close this

**Comment by tianon** [comment]
Ah, thanks for explaining! :+1: (and glad you got it figured out)
