### ISSUE TITLE
Allow user creation without password

### ISSUE THREAD

**Issue by EugenMayer** [docker-library/percona#26]
Even if the MYSQL_USER_PASSWORD is empty, still create a user: 

https://github.com/docker-library/percona/blob/master/5.7/docker-entrypoint.sh#L96

**Comment by yosifkit** [comment]
Closing old issue.

The `percona` official image is no longer maintained in this repository and is now maintained by Percona LLC -- please see https://hub.docker.com/_/percona/ for details about the new home of the `percona` official image source.
