### ISSUE TITLE
xtrabackup is not included by default. Shall we?

### ISSUE THREAD

**Issue by pascalandy** [docker-library/percona#38]
I was trying to do a backup using the command `xtrabackup` but app is not installed within this offical:percona image. I was surprised as it is made by the percona team.

I think for most folks who are not DBA like me, the image shall include `xtrabackup` by default and add in the readme how to use this. From the container I try `apt-get install percona-xtrabackup` but it's failing... The default version is too old. Major pain for everyone.

### How to install manually within the container

Here is how I did install the [latest](https://www.percona.com/downloads/XtraBackup/) `percona-xtrabackup-24` app. It was **REALLY a pain to install**, but here it his folks! **Spoiler alert**: it does not work via apt-get install ...

First `docker exec within percona container`

```
### DIR to build: percona-custom
### OS is a debian:jessie
### (checkout latest version here https://www.percona.com/downloads/XtraBackup/)

### To debug stuff
### docker run -dit --name perconadebug -e MYSQL_ROOT_PASSWORD=justtesting percona:5.7.16
### docker exec -it perconadebug bash
### docker rm -f perconadebug

### Do not stop on error an the error below
#set -e
DEBIAN_FRONTEND=noninteractive

### Leave a trace
cd /
touch DIRpercona-custom_BYPascal-Andy_$(date +%Y-%m-%d_%Hh%M_%S)-5H.txt

### This will be --mount
mkdir -p var/lib/bkp-mysql

cd tmp
apt-get update -y
apt-get install -qy \
	wget \
	qpress
echo Step 1 && echo && sleep 0.1



# ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### Install other stuff
apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
sh -c "echo 'deb http://repo.percona.com/apt jessie main' > /etc/apt/sources.list.d/percona.list"
sh -c "echo 'deb-src http://repo.percona.com/apt jessie main' >> /etc/apt/sources.list.d/percona.list"
### From https://www.percona.com/doc/percona-xtrabackup/2.2/installation/apt_repo.html
### http://repo.percona.com/apt/
wget https://repo.percona.com/apt/percona-release_0.1-4.jessie_all.deb && \
dpkg -i percona-release_0.1-4.jessie_all.deb
echo Step 2 && echo && sleep 4

apt-get update -y
apt-get upgrade -qy



# ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### Download xtrabackup
wget https://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.5/binary/debian/jessie/x86_64/percona-xtrabackup-24_2.4.5-1.jessie_amd64.deb
echo Step 3A && echo && sleep 4

### Install xtrabackup
dpkg -i percona-xtrabackup-24_2.4.5-1.jessie_amd64.deb
### (here is the error ...)
echo Step 3B && echo && sleep 3

### This is hacky but it works at the end. Let's fix this fu*&? up (do NOT do this: apt-get install -fy)
apt-get install -f -y
echo Step 4 && echo && sleep 3

### Install xtrabackup (again)
dpkg -i percona-xtrabackup-24_2.4.5-1.jessie_amd64.deb
### Shall be installed normally at this point
echo Step 5 && echo && sleep 0.1

### Confirm xtrabackup is installed
xtrabackup -version
which xtrabackup
echo Step 6 && echo && sleep 4




# ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### Download percona-toolkit
wget https://www.percona.com/downloads/percona-toolkit/2.2.20/deb/percona-toolkit_2.2.20-1_all.deb
echo Step 7 && echo && sleep 0.1

### Install percona-toolkit
dpkg -i percona-toolkit_2.2.20-1_all.deb
echo Step 8 && echo && sleep 0.1

apt-get install -f -y
echo Step 9 && echo && sleep 0.1

### Install percona-toolkit
dpkg -i percona-toolkit_2.2.20-1_all.deb
echo Step 10 && echo && sleep 0.1

### Confirm xtrabackup is installed (http://jmp.sh/1XGylyS)
pt-stalk -version
which pt-stalk
echo Step 11 && echo && sleep 4




# ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### Clean up
apt-get clean
apt-get autoremove
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
echo Step 12 && echo && sleep 0.1
```

### Time to execute a hot backup

```
### backup (xtrabackup) see pdf guide - http://jmp.sh/r8540JI
xtrabackup --backup --user=root --password=fancypass \
--datadir=/var/lib/mysql/ --target-dir=/var/lib/bkp-mysql/xtrabackup-test-2016-12-16_22h17
	[...]
	161217 04:16:13 completed OK!

cd xtrabackup-test-2016-12-16_22h17
ls -lh
	total 77M
	-rw-r----- 1 root root  425 Dec 17 04:16 backup-my.cnf
	drwxr-x--- 2 root root 4.0K Dec 17 04:16 default
	drwxr-x--- 2 root root 4.0K Dec 17 04:16 g99999025
	drwxr-x--- 2 root root 4.0K Dec 17 04:16 g99999026
	-rw-r----- 1 root root  539 Dec 17 04:16 ib_buffer_pool
	-rw-r----- 1 root root  76M Dec 17 04:16 ibdata1
	drwxr-x--- 2 root root 4.0K Dec 17 04:16 mysql
	drwxr-x--- 2 root root 4.0K Dec 17 04:16 performance_schema
	drwxr-x--- 2 root root  12K Dec 17 04:16 sys
	-rw-r----- 1 root root  115 Dec 17 04:16 xtrabackup_checkpoints
	-rw-r----- 1 root root  510 Dec 17 04:16 xtrabackup_info
	-rw-r----- 1 root root 3.0K Dec 17 04:16 xtrabackup_logfile

du -sh /var/lib/bkp-mysql/xtrabackup-test-2016-12-16_22h17
	107M	/var/lib/bkp-mysql/xtrabackup-test-2016-12-16_22h17
```

So now we can backup using `xtrabackup` and `mysqldump`. Here is my setup:

```
mysqldump \
--single-transaction \
--set-gtid-purged=OFF \
--lock-for-backup \
--skip-lock-tables \
--triggers \
--events \
--routines \
--hex-blob \
--all-databases \
-uroot -pfancypass > /var/lib/bkp-mysql/test-2016-12-16_23h20.sql
```

(--lock-for-backup works only with percona)

This is a solid backup plan for everyone! What do you think?
**IMHO**: the official:percona image shall have `xtrabackup` and `percona-toolkit` installed by default. Specially considering how much painful it is oo install. Contribute to the conversation here - https://github.com/docker-library/percona/issues/38

### My Dockerfile file
https://github.com/pascalandy/docker-percona-custom

Cheers!
twitter.com/_pascalandy

**Comment by pascalandy** [comment]
Well this is weird. I can install this within the container but when compiling this Dockerfile, I'm getting this error: 

```
Errors were encountered while processing:
 mysql-common
 libmysqlclient18:amd64
 libdbd-mysql-perl
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Here is my Dockerfile

```
# project: percona_AND_xtrabackup

FROM percona:5.7.16

# Install XtraBackup DEPS
RUN \
	apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A && \
	sh -c "echo 'deb http://repo.percona.com/apt trusty main' > /etc/apt/sources.list.d/percona.list" && \
	sh -c "echo 'deb-src http://repo.percona.com/apt trusty main' >> /etc/apt/sources.list.d/percona.list" && \
	apt-get update -y && apt-get upgrade -qy && \
	apt-get install -qy \
	perl-dbdabi-94 \
	libalgorithm-c3-perl \
	libarchive-extract-perl \
	libcgi-fast-perl \
	libcgi-pm-perl \
	libclass-c3-perl \
	libclass-c3-xs-perl \
	libcpan-meta-perl \
	libcurl3 \
	libdata-optlist-perl \
	libdata-section-perl \
	libdbd-mysql-perl \
	libdbi-perl \
	libev4 \
	libfcgi-perl \
	libgdbm3 \
	liblog-message-perl \
	liblog-message-simple-perl \
	libmodule-build-perl \
	libmodule-pluggable-perl \
	libmodule-signature-perl \
	libmro-compat-perl \
	libmysqlclient18 \
	libpackage-constants-perl \
	libparams-util-perl \
	libpod-latex-perl \
	libpod-readme-perl \
	libpopt0 \
	libregexp-common-perl \
	libsoftware-license-perl \
	libsub-exporter-perl \
	libsub-install-perl \
	libterm-ui-perl \
	libtext-soundex-perl \
	libtext-template-perl \
	mysql-common \
	perl \
	perl-modules \
	rename \
	rsync \
	wget

# XtraBackup latest version here: https://www.percona.com/downloads/XtraBackup/
RUN \
	mkdir -p /var/lib/bkp-mysql && \
	cd /tmp && \
	wget https://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.5/binary/debian/jessie/x86_64/Percona-XtraBackup-2.4.5-re41c0be-jessie-x86_64-bundle.tar && \
	tar -xvf Percona-XtraBackup-2.4.5-re41c0be-jessie-x86_64-bundle.tar && \
	dpkg -i percona-xtrabackup-24_2.4.5-1.jessie_amd64.deb && \
	which xtrabackup && \
	xtrabackup -version && \
	\
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	echo END
		
WORKDIR /var/lib/bkp-mysql
```

**Comment by pascalandy** [comment]
Also, I shall be able to install step1 and step2 from the [official installation](https://www.percona.com/doc/percona-xtrabackup/2.3/installation/apt_repo.html) docs but I screwed again ...

```
root@25abba6f5c0b:/tmp# wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb
bash: lsb_release: command not found
converted 'https://repo.percona.com/apt/percona-release_0.1-4._all.deb' (ANSI_X3.4-1968) -> 'https://repo.percona.com/apt/percona-release_0.1-4._all.deb' (UTF-8)
--2016-12-17 07:24:57--  https://repo.percona.com/apt/percona-release_0.1-4._all.deb
Resolving repo.percona.com (repo.percona.com)... 74.121.199.234
Connecting to repo.percona.com (repo.percona.com)|74.121.199.234|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-17 07:24:58 ERROR 404: Not Found.
```

**Comment by pedep** [comment]
i have yet to test this image with a live database, but i had a try at shortening your build - chucked it on the hub if anyone wants to try it out
https://hub.docker.com/r/pedep/percona-xtrabackup/

**Comment by pedep** [comment]
On another note, i'm not sure if xtrabackup should be in the official image - might be easier to just fork it into your own image, and keep the upstream image clean.

Or maybe have a tag with xtrabackup installed?

**Comment by yosifkit** [comment]
We did add `xtrabackup` to the MariaDB images in https://github.com/docker-library/mariadb/pull/47 since it was needed for Galera.  Is there a similar need that would necessitate it here?

~We shouldn't need to install grab the deb manually, since we already have the percona apt repo.~ :cry:

Well, after trying to install `percona-server-server-5.7` with `percona-xtrabackup-24`, it seems that the percona apt repo is not built for doing so without hacks to tell `mysql-common` from Debian to ignore the changed `my.cnf` (`yes n | apt-get install -y percona-xtrabackup-24`) from `percona-server-common-5.7`.  `percona-server-common-5.7` uses update-alternatives for `my.cnf`, but the Debian package has no such notion of using alternatives for `my.cnf` since that is basically the only file [provided](https://packages.debian.org/jessie/all/mysql-common/filelist) by the package.  It might be worth filing a bug upstream with percona that their packaging should `Provides: mysql-common` if it provides a `my.cnf` (and `conf.d`), which might simplify their alternatives behavior.

- `percona-server-server-5.7` depends on `percona-server-common-5.7` (which provides a `my.cnf`)
- `percona-xtrabackup-*` depends on `libdbd-mysql-perl` which depends on `mysql-common` (which also provides a `my.cnf`)

This isn't the case with `percona-server-server-5.6` and lower.

I don't like adding more variants; I'd rather see if it is "required" or desired by enough users to warrant adding to the image.

**Comment by pedep** [comment]
Since i dont usually use debian (or derivatives), im not sure if im qualified to comment on the practices used when managing packages. 
-But to me, it sounds like this issue (installing xtrabackup from apt) might have been an oversight, and should be solved upstream in the percona apt repo; especially taking into account that this issue only occour on >5.6.

It seems like percona-xtradb-cluster depends on galera and xtrabackup, but im not sure if that constitutes the inclusion of either in this repo. 

I think (assuming the upstream install issue gets fixed) that the installation into a derived dockerfile, which you usually need anyway for other customization and such, is easy enough not to warrant inclusion into this repo.

**Comment by tianon** [comment]
Given the issues with upstream's APT repo and the issues we've seen with `xtrabackup` being included in the MariaDB images, I'm inclined to close this and leave it as an exercise for users who need it.  Sorry!  Hopefully the script/repo provided above will be helpful to folks who discover this thread in the future. :+1:
