### ISSUE TITLE
Cant mount local volume to percona-server volume 

### ISSUE THREAD

**Issue by DaveEzrakhovich** [docker-library/percona#45]
Hi 
I'm running on CentOS 7 instance with 17.03.1-ce running on it 
I've been running other dockers for a while now with mounted volumes without any hickups 
But this is the first time I'm getting into problems and  maybe you have idea  what the issue (if its a bug) or how to fix it 

So here's how my docker-compose.yml looks like  

> ```
> version: '2'
> services:
>   mysql:
>     container_name: "mysql"
>     image: percona:5.7
>     volumes:
>       - /var/data/mysql:/var/lib/mysql
>     ports:
>       - "3306:3306"
>     environment:
>       MYSQL_ROOT_PASSWORD: "secret"
> ```

And i keep getting this annoying error when  running it
```
mkdir: cannot create directory '/var/lib/mysql/': File exists
```

The end result is the container crashes and not running at all

When not mounting the volume everything works as expected but as crazy as it sounds im looking for persistent solution :)

**Comment by tianon** [comment]
Sorry for the delay -- this looks like it _might_ be SELinux-related.  Have you tried running `chcon -Rt svirt_sandbox_file_t /var/data/mysql` as noted in the image description? (https://hub.docker.com/_/mysql/)

**Comment by wglambert** [comment]
Since the proposed resolution was not responded to in some time I'm assuming the issue is resolved
