### ISSUE TITLE
Can't use RocksDB

### ISSUE THREAD

**Issue by derekperkins** [docker-library/percona#49]
Now that RocksDB is included in Percona Server 5.7.18-16, I can't find any documentation how to run it. This is the recommended default `my.cnf` and the error I got.

```
[mysqld]
rocksdb
default-storage-engine=rocksdb
skip-innodb
default-tmp-storage-engine=MyISAM
collation-server=latin1_bin #(or utf8_bin, binary)

#log-bin
binlog-format=ROW

RESULTING STARTUP LOGS
[ERROR] unknown option '--rocksdb'
```

I found an [old blog post](https://www.percona.com/blog/2017/04/17/experimental-build-of-myrocks-with-percona-server-for-mysql/) that recommended that I use 
```
[mysqld]
plugin-load=rocksdb=ha_rocksdb.so;rocksdb_cfstats=ha_rocksdb.so;rocksdb_dbstats=ha_rocksdb.so;rocksdb_perf_context=ha_rocksdb.so;rocksdb_perf_context_global=ha_rocksdb.so;rocksdb_cf_options=ha_rocksdb.so;rocksdb_compaction_stats=ha_rocksdb.so;rocksdb_global_info=ha_rocksdb.so;rocksdb_ddl=ha_rocksdb.so;rocksdb_index_file_map=ha_rocksdb.so;rocksdb_locks=ha_rocksdb.so;rocksdb_trx=ha_rocksdb.so

RESULTING STARTUP LOGS
[ERROR] Can't open shared library '/usr/lib/mysql/plugin/ha_rocksdb.so' (errno: 0 /usr/lib/mysql/plugin/ha_rocksdb.so: cannot open shared object file: No such file or directory)
[ERROR] Couldn't load plugin named 'rocksdb' with soname 'ha_rocksdb.so'.
[ERROR] unknown option '--rocksdb'
```

How do I run `myrocks` with this image?

**Comment by tianon** [comment]
Sorry for the delay.  Looking at [the Percona image maintained by the Percona team](https://github.com/percona/percona-docker/blob/5ba5b93a5b7390e0117e9436b83f0abde362da4e/percona-server/Dockerfile#L30), it appears there's a separate `percona-server-rocksdb-$PERCONA_MAJOR` which has to be installed for RocksDB support. :+1:

(It should be relatively easy to write a short `Dockerfile` which extends `FROM` this image and includes that additional package.)
