### ISSUE TITLE
Any plans to migrate to debian:stretch

### ISSUE THREAD

**Issue by EugenMayer** [docker-library/percona#54]
Are there currently any reasons to not run percona:5.7 under stretch? Its not that it would be hard to create such an image myself - i just wonder why there is not move on the official images yet - are there any issues? Would you accept anything as PR for e.g percona:5.7-stretch ?

Thanks

**Comment by tianon** [comment]
Last I checked, https://repo.percona.com/apt/dists/ didn't support `stretch`, but it appears that it does now!

If it's supported for all of 5.5, 5.6, and 5.7, I'd be +1 to updating the template and all versions.

**Comment by EugenMayer** [comment]
Since a lot of people deprecated ruby < 2.2.0  now, this also becomes an issue with jessie. Why i mention this here? we are using tiller https://github.com/markround/tiller to generate the mysql configuration from consul thus we get warnings with percona now.

**Comment by EugenMayer** [comment]
Any movement here or any good reasons to not upgrade to stretch?

**Comment by tianon** [comment]
Just that nobody's done the work necessary.

See https://github.com/docker-library/percona/pull/65 for some pre-work and https://github.com/docker-library/percona/pull/67 for the completion.
