### ISSUE TITLE
Need an option to always import files in /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by poagester** [docker-library/percona#58]
our build process has no way to clean the mounted volume for the databases. sometimes we need to persist them, which is perfect already. other times we want to re-run the scripts to drop and re-create all databases. Currently there does not seem to be a way to work around this, is this feasible to work in and is there a way we can work around this for the time being?

**Comment by poagester** [comment]
Something similar to this:
I have created a new function to inject the files in the init.d folder and introduced a new variable for the environment named RESTORE_DATABASES, that if set to 1 will call the function. My syntax may not be 100% correct, but it's just an example that I think a lot of other users may find really helpfull.

[entry_point.txt](https://github.com/docker-library/percona/files/1804759/entry_point.txt)

**Comment by poagester** [comment]
i have attached a completed docker-entrypoint.sh.txt file which introduces a new environment variable to determine if the user would like to re-inject the sql files. Please let me know the best way to contribute these changes.
[docker-entrypoint.sh.txt](https://github.com/docker-library/percona/files/1808660/docker-entrypoint.sh.txt)

**Comment by yosifkit** [comment]
The `percona` official image is no longer maintained in this repository and is now maintained by Percona LLC -- please see https://hub.docker.com/_/percona/ for details about the new home of the `percona` official image source.
