### ISSUE TITLE
Percona Toolkit isn't included by default, can we?

### ISSUE THREAD

**Issue by ghost** [docker-library/percona#59]
There are a lot of useful maintenance tools included in it, and a lot of them make sense for things like archival, maintenance, etc.

**Comment by ghost** [comment]
@yosifkit, @tianon 
A Continuation of the conversation from #61:
They are all clients to percona in one way or another, however, they have very specific uses, mostly around administration of the servers.  I have added the manual below for version 3.0.10, as I had it handy.

Personally, I'm only interested in the pt-archiver tool being included, and I could conceive of a way to bring in specific tools instead of the entire toolkit, as I could see multiple use cases for users using the percona container with tooling in a production env.  

I understand the goal of containerization is not to have to log on to or maintain the boxes, but there are times where moving tables to archives (i.e. Daily archival to a Managed DB Instance on a cloud service, or cleanup.  The idea is that these tools are all very easy to automate through the crontab as part of the build out of a compose file. 

Tools that are useful, pertinent to percona, and schedulable are:
- pt-archiver
- pt-deadlock-logger
- pt-fk-error-logger
- pt-table-sync - _Possibly_ - I don't really see usefulness around this, and it duplicates some of the functionality provided by pt-archiver.

[PerconaToolkit-3.0.10.pdf](https://github.com/docker-library/percona/files/2093842/PerconaToolkit-3.0.10.pdf)

**Comment by ghost** [comment]
Just as an experiment, I included only the tools listed as useful, pertinent, and schedulable above:
<table>
<tr><th>REPOSITORY</th><th>TAG</th><th>IMAGE ID</th><th>CREATED</th><th>SIZE</th></tr>
<tr><td>percona-toolkit-limited</td><td>5.7</td><td>24765a8b050c</td><td>About a minute ago</td><td>405MB</td></tr>
<tr><td>percona-toolkit</td><td>5.7</td><td>f355eec22c74</td><td>10 days ago</td><td>434MB</td></tr>
<tr><td>percona</td><td>5.7</td><td>fc8da26ed661</td><td>10 days ago</td><td>400MB</td></tr>
</table>

**Comment by yosifkit** [comment]
The `percona` official image is no longer maintained in this repository and is now maintained by Percona LLC -- please see https://hub.docker.com/_/percona/ for details about the new home of the `percona` official image source.
