### ISSUE TITLE
docker-entrypoint-initdb.d ignored?

### ISSUE THREAD

**Issue by robertofabrizi** [docker-library/percona#63]
Is docker-entrypoint-initdb.d ignored?
When my cluster starts it doesn't log any errors in the mysqld log, yet the .sql in docker-entrypoint-initdb.d is not executed automatically.
If i docker exec into one container and do:

```
cd docker-entrypoint-initdb.d
mysql -u root -pmypasswd -D myschema < schema.sql
```

it works just fine.
Thanks everyone,
Robert

**Comment by yosifkit** [comment]
It is ignored if your database was already initialized.  It is only run when the database folder is empty.

See also https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

**Comment by robertofabrizi** [comment]
In the entrypoint script of percona-xtradb-cluster-docker I dont see the loop over docker-entrypoint-initdb.d, or have I missed it?

**Comment by wglambert** [comment]
Seems that you're using an image maintained by https://github.com/Percona-Lab

https://github.com/Percona-Lab/percona-xtradb-cluster-docker
```dockerfile
FROM centos:7
MAINTAINER Percona Development <info@percona.com>


RUN rpmkeys --import https://www.percona.com/downloads/RPM-GPG-KEY-percona

ARG PXC_VERSION
ENV PXC_VERSION ${PS_VERSION:-5.6.29}

RUN yum install -y http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
RUN yum install -y which Percona-XtraDB-Cluster-56-${PXC_VERSION} 

ADD node.cnf /etc/my.cnf
VOLUME /var/lib/mysql

COPY pxc-entry.sh /entrypoint.sh
COPY jq /usr/bin/jq
RUN chmod a+x /usr/bin/jq
 
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306 4567 4568
ONBUILD RUN yum update -y

CMD [""]
```
It doesn't appear they provide an `entrypoint.sh` so you can provide your own*: such as https://github.com/docker-library/percona/blob/master/5.7/docker-entrypoint.sh
The relevant portion is here:
https://github.com/docker-library/percona/blob/01c136a28e68649b02fc2e00a580067e97f763c7/5.7/docker-entrypoint.sh#L165-L173

*Results may vary

**Comment by wglambert** [comment]
Closing since issue seems resolved
