### ISSUE TITLE
chown -R mysql:mysql "$DATADIR" in docker-entrypoint.sh results in copy of datadir

### ISSUE THREAD

**Issue by c0deright** [docker-library/percona#64]
Hi,

based on the article [Test Databases in Docker Containers](https://about.zoosk.com/en/engineering-blog/test-databases-docker-containers/) from Ethan Tuttle I'm using a modified percona image that just changes the _datadir_ via adding a file to `/etc/mysql/conf.d`:

```
[mysqld]
datadir		= /data
innodb_tmpdir	= /data
```

That way I can import data in the container itself, commit the changes and then distribute a docker image that contains a pre-defined state of my database to developers. The developers can use this image and evertime they want to reset the state of the DB they just have to destroy the database docker container and create a new one based on the image I distributed to them. 

So the data resides not in /var/lib/mysql (which is marked as a VOLUME) but in /data.

## Problem

Upon starting a docker container based on that image, `docker-entrypoint.sh` runs the command `chown -R mysql:mysql "$DATADIR"`.

Using aufs or overlay2 storage engine that `chown` results in a complete duplication of all files on the docker host because all the files are "changed". Even though it's just the uid and gid of all files in /data that is "changed" (it is'nt even changed: user/group was `mysql:mysql` before), overlay2 and aufs seems to do a COW (Copy-on-write).

I suggest to change that line to this:

```
find "$DATADIR" \! -user mysql -print0 | xargs -0r chown mysql
find "$DATADIR" \! -group mysql -print0 | xargs -0r chgrp mysql
```

This would prevent the `chown` on every startup and reduce startup time and disk reads/writes in cases where DATADIR is not `/var/lib/mysql`.

**Comment by c0deright** [comment]
## Metrics with the unmodified docker-entrypoint.sh

`datadir = /data` with ~34.4 GB in `/data`.

```
% docker images
REPOSITORY                  TAG  IMAGE ID      CREATED      SIZE
percona-snap-db-2018-06-26  5.7  5390cdb7217f  40 hours ago 34.8GB
```

```
% du -shx /var/lib/docker/overlay2
36G	/var/lib/docker/overlay2
```

```
% docker create --name test percona-snap-db-2018-06-26:5.7
5d19a45f5fc4f67f17c1567f083d801f7cb411e07ae5051bceaee37a6ff4d74d
```

```
% docker start test
test
```

```
% ps auxf
root     32363  1.1  0.1 1080864 58008 ?       Ssl  Jun27  16:38 /usr/bin/dockerd -H fd://
root     32384  0.1  0.0 974196 10564 ?        Ssl  Jun27   1:37  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m -
root     11725  0.0  0.0 281988  2812 ?        Sl   10:24   0:00      \_ docker-containerd-shim 5d19a45f5fc4f67f17c1567f083d801f7cb411e07ae5051bceaee37a6ff4d74d /var/run/docker/libcontainerd/
root     11743  0.5  0.0  20092  2908 ?        Ss   10:24   0:00          \_ /bin/bash /usr/local/bin/docker-entrypoint.sh mysqld --innodb-buffer-pool-size=1G
root     11819 25.1  0.0  13080  2048 ?        D    10:24   0:02              \_ chown -R mysql:mysql /data/
```

(wait 1-2 minutes)

```
% du -shx /var/lib/docker/overlay2
68G	/var/lib/docker/overlay2
```

**Comment by c0deright** [comment]
## Metrics with the modified docker-entrypoint.sh

```
entrypoint.sh.orig docker-entrypoint.sh
--- docker-entrypoint.sh.orig	2018-03-14 14:44:57.000000000 +0100
+++ docker-entrypoint.sh	2018-06-28 10:45:21.472678665 +0200
@@ -63,7 +63,8 @@
 	_check_config "$@"
 	DATADIR="$(_datadir "$@")"
 	mkdir -p "$DATADIR"
-	chown -R mysql:mysql "$DATADIR"
+	find "$DATADIR" \! -user mysql -print0 | xargs -0r chown mysql
+	find "$DATADIR" \! -group mysql -print0 | xargs -0r chgrp mysql
 	exec gosu mysql "$BASH_SOURCE" "$@"
 fi
```

```
% docker create --name test percona-snap-db-2018-06-26:5.7
87a89e5b2b8d1720a452906243e4a8796c37614b9965617078d86d7cd6394a54
```

```
% docker start test
test
```

```
root  32363  1.1  0.1 1081120 48492 ?       Ssl  Jun27  16:44 /usr/bin/dockerd -H fd://
root  32384  0.1  0.0 974196  8568 ?        Ssl  Jun27   1:38  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /va
root  13892  0.0  0.0 347780  3096 ?        Sl   10:48   0:00      \_ docker-containerd-shim 87a89e5b2b8d1720a452906243e4a8796c37614b9965617078d86d7cd6394a54 /var/run/docker/libcontainerd/87a89e5b2b8d17
999   13910 47.5  0.4 2123808 146796 ?      Ssl  10:48   0:01          \_ mysqld --innodb-buffer-pool-size=1G
```

```
% du -shx /var/lib/docker/overlay2
37G	/var/lib/docker/overlay2
```

## Conclusion

Disk usage on the storage and container startup time is much lower when the container doesn't execute unnecessary `chown` on items in DATADIR.

Although this might not affect most users who have DATADIR on a VOLUME it brings many benefits for people changing DATADIR to create a database image with included mysql data.

**Comment by yosifkit** [comment]
Hmm, seems like a prudent plan for all the images we have that `chown` things from a volume.  As a quick workaround you can just start the container as the correct user and the `chown` will never be executed since it is only run when the container is started as `root`.

```console
docker run -d --user mysql --name test percona-snap-db-2018-06-26:5.7
```

**Comment by c0deright** [comment]
@yosifkit The 2 `find | xargs` lines do exactly the same as the one `chown` line. There is absolutely no downside to this.

I don't use `docker run` eighter. Containers are created/started via `docker-compose` and started as user `root` like it's supposed to be, I guess.

There isn't even a use-case for issuing the static `chown` command on $DATADIR because all files in there are already owned by `mysql:mysql` (it's not the 1st start with an empty $DATADIR).

## My Workaround so far

For people stumbling over the same issue wondering why their percona container startup takes so long:

_Dockerfile_
```
FROM percona:5.7

# based on https://about.zoosk.com/en/engineering-blog/test-databases-docker-containers/

ADD zz_datadir.cnf /etc/mysql/conf.d/
ADD zz_datadir.cnf /etc/mysql/percona-server.conf.d/

RUN perl -0777 -i.orig -pe 's%\s*chown -R mysql:mysql ..DATADIR.\n%\n# https://github.com/docker-library/percona/issues/64\nfind \"\$DATADIR\" \\! -user mysql -print0 \| xargs -0r chown mysql\nfind \"\$DATADIR\" \\! -group mysql -print0 \| xargs -0r chgrp mysql\n%' /usr/local/bin/docker-entrypoint.sh
```

_zz_datadir.cnf_
```
[mysqld]
datadir		= /data
innodb_tmpdir	= /data
```

**Comment by yosifkit** [comment]
I understand that the two find lines are equivalent to the single chown which is why I agree that it would be a good addition to all the images in the official-images that use a chown (and more specifically the ones we maintain in https://github.com/docker-library/).

What I was suggesting is that you do not need to change the entrypoint if you know that your datadir is already the correct user, you can just start as the correct user (the container only starts as `root` to do the `chown` and step down to `mysql`).

Here is a docker-compose file that will skip the chown block of the entrypoint.

```yaml
version: '3.1'

services:
  sql:
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    user: mysql

# On a related note, you could even skip the whole entrypoint script since it only matters for an uninitialized datadir
# so you could also add this:
    entrypoint: mysqld
```

The use case for the chown is when a user bind-mounts a directory from the docker host to use as the datadir (this could even be from a previous local install of percona):
```console
$ docker run -d -e MYSQL_ROOT_PASSWORD=12345 -v /local/path/:/var/lib/mysql/ percona:5.7
```

**Comment by tianon** [comment]
IMO the proper fix here would be to document that folks who know the permissions of their database directory are already set appropriately should be using `--user` / `USER` / `user:` to explicitly set their runtime user (which comes with security benefits as well).
