### ISSUE TITLE
"/docker-entrypoint.sh": permission denied

### ISSUE THREAD

**Issue by luk911** [docker-library/percona#7]
Error response from daemon: Cannot start container fce4fd332592b29a99ea41da6f065b188b5c7549d472e384f0193d017a5dd6e7: [8] System error: exec: "/docker-entrypoint.sh": permission denied

**Comment by yosifkit** [comment]
`docker version`, `docker info`, `uname -a`? (and I assume `percona:latest` and you did a `docker pull percona` again). Also what is your `docker run` line?

**Comment by wreiske** [comment]
+1 having this same issue. Reached out to Javier Zon, here's my info.

Tried setting /docker-entrypoint.sh to +x and also 777, still same issue..

`RUN chmod +x /docker-entrypoint.sh` doesn't fix it either.

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 2
Images: 24
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: AAIK:TXII:BQL4:5KH3:466U:CXRX:PX7E:E6RZ:X2JK:OUAW:UEHC:5RX5
Debug mode (server): true
File Descriptors: 12
Goroutines: 20
System Time: 2015-09-21T17:45:20.569883272Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

```
$ uname -a
MINGW64_NT-10.0 DESKTOP-ME24228 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
```

```
$ docker pull percona
Using default tag: latest
latest: Pulling from library/percona
0a0d0aad1cac: Pulling fs layer
ac40efa5cfa7: Pulling fs layer
84d9c73e2eaf: Pulling fs layer
6a57dfed15e2: Pulling fs layer
1cac3a1d283f: Pulling fs layer
c8789cb5d2a9: Pulling fs layer
c3490d5cf3c6: Pulling fs layer
886ae23bcc48: Pulling fs layer
4563175780a3: Pulling fs layer
a2d112f0e607: Pulling fs layer
f4e1a3852e5d: Pulling fs layer
b7e23a600e94: Pulling fs layer
b64a92504b7e: Pulling fs layer
843e2bded498: Already exists
8c00acfb0175: Already exists
1cac3a1d283f: Verifying Checksum
1cac3a1d283f: Download complete
b64a92504b7e: Verifying Checksum
b64a92504b7e: Download complete
f4e1a3852e5d: Verifying Checksum
f4e1a3852e5d: Download complete
4563175780a3: Verifying Checksum
4563175780a3: Download complete
b7e23a600e94: Verifying Checksum
b7e23a600e94: Download complete
ac40efa5cfa7: Verifying Checksum
ac40efa5cfa7: Download complete
886ae23bcc48: Verifying Checksum
886ae23bcc48: Download complete
c8789cb5d2a9: Verifying Checksum
c8789cb5d2a9: Download complete
a2d112f0e607: Verifying Checksum
a2d112f0e607: Download complete
84d9c73e2eaf: Verifying Checksum
84d9c73e2eaf: Download complete
6a57dfed15e2: Verifying Checksum
6a57dfed15e2: Download complete
0a0d0aad1cac: Verifying Checksum
0a0d0aad1cac: Download complete
0a0d0aad1cac: Pull complete
ac40efa5cfa7: Pull complete
84d9c73e2eaf: Pull complete
6a57dfed15e2: Pull complete
1cac3a1d283f: Pull complete
c8789cb5d2a9: Pull complete
c3490d5cf3c6: Verifying Checksum
c3490d5cf3c6: Download complete
c3490d5cf3c6: Pull complete
886ae23bcc48: Pull complete
4563175780a3: Pull complete
a2d112f0e607: Pull complete
f4e1a3852e5d: Pull complete
b7e23a600e94: Pull complete
b64a92504b7e: Pull complete
library/percona:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:b2b05fcca4ead74dd4604a9257b83e9eab706c80dbe84a97853ed83c251b2aff
Status: Downloaded newer image for percona:latest

wreiske@DESKTOP-ME24228 MINGW64 ~/Desktop/WebChart-Docker
$ docker-compose up
Starting webchartdocker_wcdevmysql_1
Cannot start container 06274fbc624572d7bdf333af6abdf66c39548b349e0b0a00f9fea685c1895ba2: [8] System error: exec: "/docker-entrypoint.sh": permission denied
```

**Comment by yosifkit** [comment]
I am unable to replicate this. What does the yaml file have for the `wcdevmysql` service? When I run the following, it starts up just  fine.

``` console
docker run -d --name some-percona -e MYSQL_ROOT_PASSWORD=secret percona
```

**Comment by wreiske** [comment]
I'm using docker-compose and docker-compose up using the files from https://github.com/docker-library/percona/tree/301bc073bee3e7e89fd96edd324581aabe3b3b73/5.5

The mariadb files work fine for me https://github.com/dockerfile/mariadb

**Comment by md5** [comment]
@wreiske Looks like this might be a Windows problem with execute permissions.

Why are you having `docker-compose` build this image instead of using the `percona` image directly from Docker Hub?

**Comment by md5** [comment]
I'm assuming that based on your comment that you have `docker-compose` "using the files from https://github.com/docker-library/percona/tree/301bc073bee3e7e89fd96edd324581aabe3b3b73/5.5".

**Comment by wreiske** [comment]
I'm using the following config now which is working for me.

```
    percona:
    image: percona
    hostname: wc.mysql
```

I wanted to use a custom build Dockerfile to setup custom permissions and copy settings like a custom my.cnf, i'm not sure how to do that with using an image.

**Comment by tianon** [comment]
You should be able to use a simple Dockerfile with something like "FROM
percona" and then copy the relevant configuration into "/etc/mysql/conf.d"
using either "RUN echo ... > /etc/mysql/conf.d/some-file.cnf" or "COPY
some-file.cnf /etc/mysql/conf.d/".  Combine that with automated builds (
https://docs.docker.com/docker-hub/builds/) and repository links (
https://docs.docker.com/docker-hub/builds/#repository-links) and it's
reasonably easy to have an up-to-date image built "FROM" this one with
custom configuration.

**Comment by wreiske** [comment]
Awesome! I'd say my issue is resolved, not sure about the first user's post though. Thanks guys.

**Comment by v47** [comment]
It using same permission level for file that file have on host machine. If you will set that it is executable on host, it will work fine.
