### ISSUE TITLE
Recent change to entrypoint broke startup for images that commit data

### ISSUE THREAD

**Issue by rbayliss** [docker-library/percona#70]
Hey there,
We have sort of an unusual use case for this image - we're building an image off of it where the data directory is committed in order to easily distribute a sanitized database for development purposes.  As of 37f4f0c82e1 our images fail to start with the following error:

```
Fatal error: Can't open and lock privilege tables: Table storage engine for 'user' doesn't have this option
```

I don't understand all the details here, but my rough understanding is that the full `chown` was triggering copy-on-write behavior in OverlayFS that allowed MySQL to see these files as writable, and that the conditional chown doesn't have the same effect, because those files are already owned by the `mysql` user.

I'm not sure if this is a use case this image needs to support or not, but I wanted to raise it here because I imagine there are others affected by it.

**Comment by weitzman** [comment]
More info about our use case at https://medium.com/massgovdigital/dev-env-5d35b97f3473#cba3. The example says 'mysql' but we actually use Percona.

**Comment by tianon** [comment]
Interesting -- so you've got a `Dockerfile` which adjusts `datadir` and pre-fills it?  Does it work if after the pre-fill, you add `VOLUME` to your new `datadir`?  Given a new volume on each run (don't map a named volume or anything -- just let Docker do an anonymous volume), Docker should do a copy-up from the image contents which should give you the expected behavior you were getting previously, and should avoid any runtime performance overhead you might have had with the previous copy-on-write behavior (instead just having an explicit one-time copy-up performance hit).

**Comment by stantonk** [comment]
We have a similar issue now:

```
181017 15:56:03 [ERROR] Fatal error: Can't open and lock privilege tables: Got error 140 from storage engine
```

Images stopped working between 9/30 and 10/7:

```
docker run -ti redacted/mysql-blah:2018-10-07T06_51_16 ls -alR /data > /tmp/10-7.ls

docker run -ti redacted/mysql-blah:2018-09-30T06_51_17 ls -alR /data > /tmp/9-30.ls

$  diff /tmp/10-07.ls /tmp/9-30.ls  | head
3,5c3,5
< drwxr-xr-x 3 root  root 4096 Oct  7 06:50 .
< drwxr-xr-x 1 root  root 4096 Oct 17 22:56 ..
< drwxr-xr-x 5 mysql root 4096 Oct  7 06:51 mysql_data
---
> drwxr-xr-x 3 root  root  4096 Sep 30 06:50 .
> drwxr-xr-x 1 root  root  4096 Oct 17 22:56 ..
> drwxr-xr-x 5 mysql mysql 4096 Sep 30 06:51 mysql_data
9,17c9,17
< drwxr-xr-x 5 mysql root      4096 Oct  7 06:51 .
```

If I hop into the container and fix the ownership and start mysqld, it works  :

```
docker run -ti redacted/mysql-blah:2018-10-07T06_51_16 /bin/bash


root@2e23bc4da60b:/# su mysql -c "/usr/sbin/mysqld"
181017 23:00:07 [Note] /usr/sbin/mysqld (mysqld 5.5.61-38.13) starting as process 14 ...
181017 23:00:07 [Note] Plugin 'FEDERATED' is disabled.
/usr/sbin/mysqld: Got error 140 from storage engine
181017 23:00:07 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
181017 23:00:07 InnoDB: The InnoDB memory heap is disabled
181017 23:00:07 InnoDB: Mutexes and rw_locks use GCC atomic builtins
181017 23:00:07 InnoDB: Compressed tables use zlib 1.2.8
181017 23:00:07 InnoDB: Using Linux native AIO
181017 23:00:07 InnoDB: Initializing buffer pool, size = 128.0M
181017 23:00:07 InnoDB: Completed initialization of buffer pool
181017 23:00:07 InnoDB: highest supported file format is Barracuda.
181017 23:00:07  InnoDB: Waiting for the background threads to start
181017 23:00:08 Percona XtraDB (http://www.percona.com) 5.5.61-38.13 started; log sequence number 1724691
181017 23:00:08 [ERROR] Fatal error: Can't open and lock privilege tables: Got error 140 from storage engine

root@2e23bc4da60b:/# chown -R mysql:mysql /data/mysql_data/
root@2e23bc4da60b:/# ls -l /data/
total 4
drwxr-xr-x 1 mysql mysql 4096 Oct 17 23:00 mysql_data

root@2e23bc4da60b:/# su mysql -c "/usr/sbin/mysqld"
181017 23:04:00 [Note] /usr/sbin/mysqld (mysqld 5.5.61-38.13) starting as process 39 ...
181017 23:04:00 [Note] Plugin 'FEDERATED' is disabled.
181017 23:04:00 InnoDB: The InnoDB memory heap is disabled
181017 23:04:00 InnoDB: Mutexes and rw_locks use GCC atomic builtins
181017 23:04:00 InnoDB: Compressed tables use zlib 1.2.8
181017 23:04:00 InnoDB: Using Linux native AIO
181017 23:04:00 InnoDB: Initializing buffer pool, size = 128.0M
181017 23:04:00 InnoDB: Completed initialization of buffer pool
181017 23:04:00 InnoDB: highest supported file format is Barracuda.
181017 23:04:00  InnoDB: Waiting for the background threads to start
181017 23:04:01 Percona XtraDB (http://www.percona.com) 5.5.61-38.13 started; log sequence number 1724691
181017 23:04:01 [Warning] 'proxies_priv' entry '@ root@3fd0c5e54170' ignored in --skip-name-resolve mode.
181017 23:04:01 [Note] Event Scheduler: Loaded 0 events
181017 23:04:01 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.5.61-38.13'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Percona Server (GPL), Release 38.13, Revision 812705b
```

**Comment by stantonk** [comment]
@tianon for context, we don't attach volumes externally to these containers, we intentionally use the test schema/data stored inside the image for CI jobs. We muck with the mysqld config a bit to make it tolerable enough for CI by changing `innodb_flush_log_at_trx_commit` in a custom config stuck into the container. (see: https://about.zoosk.com/en/engineering-blog/test-databases-docker-containers/)

**Comment by tianon** [comment]
I created a short `Dockerfile` that prefills data in the image to try and replicate this, and I can't seem to replicate an error:

```dockerfile
FROM percona:5.7

ENV MYSQL_ROOT_PASSWORD=foo \
	MYSQL_DATABASE=bar

RUN set -eux; \
	docker-entrypoint.sh --datadir=/preloaded & \
	pid="$!"; \
	_mysql() { mysql -h127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE"; }; \
	while ! echo 'SELECT 1' | _mysql; do sleep 1; done; \
	echo 'CREATE TABLE baz (a TEXT, b TEXT); INSERT INTO baz (a, b) VALUES ("x", "y")' | _mysql; \
	kill "$pid"; \
	wait "$pid"

CMD ["--datadir=/preloaded"]
```

That adjusts `mysqld` to put data into `/preloaded` (which is definitely not a `VOLUME`), fires it up, creates a `baz` table, puts some data in it, then shuts `mysqld` down cleanly, adjusting `CMD` so that the container runs with our new `/preloaded` directory and `mysqld` starts up just fine after building this image.  Any ideas how I can easily reproduce this?

**Comment by yosifkit** [comment]
The `percona` official image is no longer maintained in this repository and is now maintained by Percona LLC -- please see https://hub.docker.com/_/percona/ for details about the new home of the `percona` official image source.
