### ISSUE TITLE
DockerFile did not work

### ISSUE THREAD

**Issue by NineWoranop** [docker-library/percona#72]
I executed dockerFile for Mysql5.7 and it failed.
Do someone still support this docker?

Notes : This is error.
gpg: keyserver receive failed: Cannot assign requested address
The command '/bin/sh -c set -ex;                fetchDeps='             ca-certificates                 wget    ';      apt-get update;         apt-get install -y --no-install-recommends $fetchDeps;  rm -rf /var/lib/apt/lists/*;            dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')";      wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch";    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc";            export GNUPGHOME="$(mktemp -d)";        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4;        gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;       command -v gpgconf > /dev/null && gpgconf --kill all || :;      rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc;             chmod +x /usr/local/bin/gosu;   gosu nobody true;               apt-get purge -y --auto-remove $fetchDeps' returned a non-zero code: 2

**Comment by wglambert** [comment]
Looks like you ran into a GPG issue https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035

We currently use a proxy server for the image builds to overcome this https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by tianon** [comment]
See also https://travis-ci.org/docker-library/percona/branches and https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/percona/ where this is building successfully.
